### ISSUE TITLE
Thesis.md: Correct typo

### ISSUE THREAD

**Issue by co-robo** [coala/projects#418] opened 2017-11-14 00:39 UTC
line 6 of _faq/thesis.md has a typo in recommend
difficulty/newcomer
Opened by @Mixih at [Gitter](https://gitter.im/coala/coala?at=5a0a3b4871ad3f8736de9c1e)

**Comment by gureks** [comment] 2017-11-14 11:55
This is a duplicate of #411 and was closed in #412

**Closed** 2017-11-14 13:05 UTC
Labels: difficulty/newcomer
