### ISSUE TITLE
Application Template typo

### ISSUE THREAD

**Issue by ishanSrt** [coala/projects#474] opened 2018-03-14 10:28 UTC
and ~~to~~ you have any preference for a particular mentor? --> and **do** you have any preference for a particular mentor?

**Comment by sbeesm** [comment] 2018-03-18 04:19
Hi! New comer here. Can i fix this?

**Comment by sbeesm** [comment] 2018-03-18 06:12
Hello! New comer here. I would like to work on this, so please assign this issue to me.

**Comment by ishanSrt** [comment] 2018-03-18 06:14
@sbeesm put a comment for assignment over here https://gitter.im/coala/coala too and start working!

**Closed** 2018-03-18 13:17 UTC
Labels: difficulty/newcomer

**Comment by jayvdb** [comment] 2018-03-18 13:20
Duplicate of https://github.com/coala/projects/issues/268
