### ISSUE TITLE
Tabs don't change while going back, though the page changes.

### ISSUE THREAD

**Issue by aalind0** [coala/projects#179] opened 2017-02-05 13:12 UTC
If we switch tabs(like projects, mentors, FAQ) on http://projects.coala.io/#/projects and then try to go back, the black highlighter stays on the latest page only and doesn't move while the page changes.

Like as shown in the image although we are on the projects page but mentors tab is highlighted.

![ment](https://cloud.githubusercontent.com/assets/13695616/22626415/d33427b6-ebd2-11e6-8135-f3ab9bceaa71.JPG)

**Comment by RaiVaibhav** [comment] 2017-11-07 06:38
I want to work on this

**Comment by prashant0598** [comment] 2017-11-16 15:51
@aalind0 i think this bug has been solved as i did not face this issue so close this issue.

**Comment by RaiVaibhav** [comment] 2017-11-16 16:05
No its not solved can you recheck @prashant0598

**Comment by AkshJain99** [comment] 2018-12-07 08:11
I think this issue has been solved as i m also not facing any problem stated in issue

**Comment by RJ722** [comment] 2018-12-07 15:54
I can reproduce this @AkshJain99.

**Comment by AkshJain99** [comment] 2018-12-07 15:55
@RJ722 how can you please tell are you facing that problem?

**Comment by RJ722** [comment] 2018-12-07 15:58
Follow these steps:
- Go to http://projects.coala.io/#/projects
- Change the tab to let's say "Mentors".
- Click the back button

Now, the page would show the projects, but the Mentors tab would still be highlighted.

**Comment by AkshJain99** [comment] 2018-12-07 16:03
@aalind0 yes now I can see that

**Comment by AkshJain99** [comment] 2018-12-07 16:03
so if no one working on the issue i would like to work

**Comment by AkshJain99** [comment] 2018-12-07 17:31
Thanks :+1: :

**Comment by AkshJain99** [comment] 2018-12-09 15:19
can anybody tell me if this issue is solvable or not as i think this is this problem is of jekyll theme and not the code
i dont think that solution is in code of this repo
if someone can help me about this please tell me that it is the issue of code or jekyll theme that we are using in the project

@aalind0 @RJ722 @li-boxuan

**Comment by jayvdb** [comment] 2019-08-25 16:38
No longer necessary due to other UI changes.
Apologies that the fix wasnt merged while the bug existed.

**Closed by jayvdb** 2019-08-25 16:38 UTC
Labels: bug, difficulty/low
