### ISSUE TITLE
Fix typo in thesis.md

### ISSUE THREAD

**Issue by co-robo** [coala/projects#411] opened 2017-11-07 17:41 UTC
There is typo in file `_faq/thesis.md`, `recommend` is misspelled as `recoment`
label: difficulty/newcomer
Opened by @Monal5031 at [Gitter](https://gitter.im/coala/coala-bears?at=5a01f04ee44c43700acb6e9d)

**Comment by prnvdixit** [comment] 2017-11-08 04:15
Duplicate of https://github.com/coala/projects/issues/240.
@Monal5031 Please, use github-search before creating an issue to check if it is an already existing issue or not. 👍
@Lucifer24 There is already an assignee at original issue. Though, he hasn't submitted a PR yet 😄.

**Comment by Monal5031** [comment] 2017-11-08 04:43
@prnvdixit Sorry my bad don't know how I missed that issue 😓

**Closed** 2017-11-09 18:36 UTC
Labels: difficulty/newcomer
