### ISSUE TITLE
Links to gitmate docs not being resolved

### ISSUE THREAD

**Issue by virresh** [coala/projects#518] opened 2018-03-23 17:20 UTC
http://code.gitmate.io is down due to which builds are failing on the projects repo.

See https://github.com/coala/projects/pull/513
or any recent PR in projects repo

Possible fix: replace the links with actual path
e.g
http://docs.gitmate.io/Developers/Writing_Plugin/ -> https://gitlab.com/gitmate/documentation/blob/master/docs/Developers/Writing_Plugin.md

**Comment by jayvdb** [comment] 2018-03-24 10:30
http://code.gitmate.io is now up, but the links are now 404

**Comment by jayvdb** [comment] 2018-03-24 10:32
@virresh & @nkprince007 , if the problem isnt fixed in a few hours, please add ignore rules to this repos `.coafile` to get past this problem.

**Comment by virresh** [comment] 2018-03-24 17:10
@jayvdb 
The 404 errors haven't been resolved yet, should we wait more or add ignore rules ?

**Comment by nkprince007** [comment] 2018-03-24 23:03
Resolved now. Please proceed. I'm closing this issue now.

**Closed** 2018-03-25 01:45 UTC
