### ISSUE TITLE
Typo in the "thesis" faq

### ISSUE THREAD

**Issue by satwikkansal** [coala/projects#240] opened 2017-03-04 11:20 UTC
![image](https://cloud.githubusercontent.com/assets/10217535/23578343/879898ae-00fa-11e7-93d8-349c2abd7b8b.png)

difficulty/newcomer

**Comment by jayvdb** [comment] 2017-11-01 15:19
Unassigned due to inactivity

**Comment by RaiVaibhav** [comment] 2017-11-12 07:05
IMO it should mark only `difficulty/newcomer`

**Comment by prnvdixit** [comment] 2017-11-14 13:54
Though https://github.com/coala/projects/issues/411 was duplicate of this one, but someone submitted a PR to that duplicate issue - This should be closed now.

**Closed** 2017-11-15 23:38 UTC
Labels: difficulty/low, difficulty/newcomer
